import {
  ArrayCompact, ArrayFlatten, ArrayJoin, ArrayUnique, Count,
  CountA, CountAll, ArraySum, ArrayAverage, ArrayMax,
  ArrayMin, ArraySlice, ArrayReverse, ArrayIncludes, ArrayCount,
  ArrayFirst, ArrayLast, ArraySort, ArrayIndexOf, ArrayDiff,
  ArrayLength, ArrayHead, ArrayTail, ArrayIntersect, ArrayUnion,
} from './array';
import type { FormulaFunc } from './common';
import { FunctionName } from './common';
import {
  CreatedTime, DateAdd, Datestr, DatetimeDiff, DatetimeFormat,
  DatetimeParse, Day, FromNow, Hour, IsAfter,
  IsBefore, IsSame, LastModifiedTime, Minute, Month,
  Now, Second, Timestr, ToNow, Today,
  WeekNum, Weekday, Workday, WorkdayDiff, Year,
  Quarter, IsoWeekNum, DayOfYear, SetDate, SetTime,
  MakeDate, MakeTime, FormatDuration, DateSubtract, StartOfMonth,
  EndOfMonth, StartOfWeek, EndOfWeek, StartOfYear, EndOfYear,
  DatetimeIsValid, UnixTimestamp, FromUnixTimestamp,
} from './date-time';
import {
  And, Blank, FormulaError, If, IsError,
  Not, Or, Switch, Xor, IsBlank,
  IfBlank, IfError, True, False, IsNumber,
  IsText, IsDate, IsNaN, IsFinite,
} from './logical';
import {
  Abs, Average, Ceiling, Even, Exp,
  Floor, Int, Log, Max, Min,
  Mod, Odd, Power, Round, RoundDown,
  RoundUp, Sqrt, Sum, Value, Sign,
  Fact, Trunc, Frac, Negate, Cbrt,
  Ln, Log2, Log10, Pi, Tau,
  Sin, Cos, Tan, Asin, Acos,
  Atan, Atan2, Sinh, Cosh, Tanh,
  Degrees, Radians, Mround, Combin, Permut,
  Quotient, Clamp, Rand, RandBetween, Gcd,
  Lcm, Product, Sumsq, Hypot, Median,
  Large, Small, Stdev, Var,
  VarP,
  StdevP,
} from './numeric';
import {
  AutoNumber, RecordId, TextAll, CreatedBy, LastModifiedBy,
} from './system';
import {
  Concatenate, EncodeUrlComponent, Find, Left, Len,
  Lower, Mid, RegExpReplace, Replace, Rept,
  Right, Search, Substitute, T, TextBefore,
  TextSplit, Trim, Upper, Char, Code,
  Exact, Proper, Clean, Dollar, Fixed,
  RegExpMatch, RegExpExtract, TextAfter, Contains, StartsWith,
  EndsWith, PadStart, PadEnd, Bin2Dec, Dec2Bin,
  Oct2Dec, Dec2Oct, Hex2Dec, Dec2Hex, NumberFormat,
  HtmlEncode, HtmlDecode, Base64Encode, Base64Decode, UrlDecode,
  Repeat,
  Concat,
} from './text';

// eslint-disable-next-line @typescript-eslint/naming-convention
export const FUNCTIONS: Record<FunctionName, FormulaFunc> = {
  // Numeric
  [FunctionName.Sum]: new Sum(),
  [FunctionName.Average]: new Average(),
  [FunctionName.Max]: new Max(),
  [FunctionName.Min]: new Min(),
  [FunctionName.Round]: new Round(),
  [FunctionName.RoundUp]: new RoundUp(),
  [FunctionName.RoundDown]: new RoundDown(),
  [FunctionName.Ceiling]: new Ceiling(),
  [FunctionName.Floor]: new Floor(),
  [FunctionName.Even]: new Even(),
  [FunctionName.Odd]: new Odd(),
  [FunctionName.Int]: new Int(),
  [FunctionName.Abs]: new Abs(),
  [FunctionName.Sqrt]: new Sqrt(),
  [FunctionName.Power]: new Power(),
  [FunctionName.Exp]: new Exp(),
  [FunctionName.Log]: new Log(),
  [FunctionName.Mod]: new Mod(),
  [FunctionName.Value]: new Value(),

  // Text
  [FunctionName.Concatenate]: new Concatenate(),
  [FunctionName.Find]: new Find(),
  [FunctionName.Search]: new Search(),
  [FunctionName.Mid]: new Mid(),
  [FunctionName.Left]: new Left(),
  [FunctionName.Right]: new Right(),
  [FunctionName.Replace]: new Replace(),
  [FunctionName.RegExpReplace]: new RegExpReplace(),
  [FunctionName.Substitute]: new Substitute(),
  [FunctionName.TextBefore]: new TextBefore(),
  [FunctionName.TextSplit]: new TextSplit(),
  [FunctionName.Lower]: new Lower(),
  [FunctionName.Upper]: new Upper(),
  [FunctionName.Rept]: new Rept(),
  [FunctionName.Trim]: new Trim(),
  [FunctionName.Len]: new Len(),
  [FunctionName.T]: new T(),
  [FunctionName.EncodeUrlComponent]: new EncodeUrlComponent(),

  // Logical
  [FunctionName.If]: new If(),
  [FunctionName.Switch]: new Switch(),
  [FunctionName.And]: new And(),
  [FunctionName.Or]: new Or(),
  [FunctionName.Xor]: new Xor(),
  [FunctionName.Not]: new Not(),
  [FunctionName.Blank]: new Blank(),
  [FunctionName.Error]: new FormulaError(),
  [FunctionName.IsError]: new IsError(),

  // DateTime
  [FunctionName.Today]: new Today(),
  [FunctionName.Now]: new Now(),
  [FunctionName.Year]: new Year(),
  [FunctionName.Month]: new Month(),
  [FunctionName.WeekNum]: new WeekNum(),
  [FunctionName.Weekday]: new Weekday(),
  [FunctionName.Day]: new Day(),
  [FunctionName.Hour]: new Hour(),
  [FunctionName.Minute]: new Minute(),
  [FunctionName.Second]: new Second(),
  [FunctionName.FromNow]: new FromNow(),
  [FunctionName.ToNow]: new ToNow(),
  [FunctionName.DatetimeDiff]: new DatetimeDiff(),
  [FunctionName.Workday]: new Workday(),
  [FunctionName.WorkdayDiff]: new WorkdayDiff(),
  [FunctionName.IsSame]: new IsSame(),
  [FunctionName.IsAfter]: new IsAfter(),
  [FunctionName.IsBefore]: new IsBefore(),
  [FunctionName.DateAdd]: new DateAdd(),
  [FunctionName.Datestr]: new Datestr(),
  [FunctionName.Timestr]: new Timestr(),
  [FunctionName.DatetimeFormat]: new DatetimeFormat(),
  [FunctionName.DatetimeParse]: new DatetimeParse(),
  [FunctionName.CreatedTime]: new CreatedTime(),
  [FunctionName.LastModifiedTime]: new LastModifiedTime(),

  // Array
  [FunctionName.CountAll]: new CountAll(),
  [FunctionName.CountA]: new CountA(),
  [FunctionName.Count]: new Count(),
  [FunctionName.ArrayJoin]: new ArrayJoin(),
  [FunctionName.ArrayUnique]: new ArrayUnique(),
  [FunctionName.ArrayFlatten]: new ArrayFlatten(),
  [FunctionName.ArrayCompact]: new ArrayCompact(),

  // System
  [FunctionName.TextAll]: new TextAll(),
  [FunctionName.RecordId]: new RecordId(),
  [FunctionName.AutoNumber]: new AutoNumber(),
  [FunctionName.CreatedBy]: new CreatedBy(),
  [FunctionName.LastModifiedBy]: new LastModifiedBy(),

  // Numeric (extended)
  [FunctionName.Sign]: new Sign(),
  [FunctionName.Fact]: new Fact(),
  [FunctionName.Trunc]: new Trunc(),
  [FunctionName.Frac]: new Frac(),
  [FunctionName.Negate]: new Negate(),
  [FunctionName.Cbrt]: new Cbrt(),
  [FunctionName.Ln]: new Ln(),
  [FunctionName.Log2]: new Log2(),
  [FunctionName.Log10]: new Log10(),
  [FunctionName.Pi]: new Pi(),
  [FunctionName.Tau]: new Tau(),
  [FunctionName.Sin]: new Sin(),
  [FunctionName.Cos]: new Cos(),
  [FunctionName.Tan]: new Tan(),
  [FunctionName.Asin]: new Asin(),
  [FunctionName.Acos]: new Acos(),
  [FunctionName.Atan]: new Atan(),
  [FunctionName.Atan2]: new Atan2(),
  [FunctionName.Sinh]: new Sinh(),
  [FunctionName.Cosh]: new Cosh(),
  [FunctionName.Tanh]: new Tanh(),
  [FunctionName.Degrees]: new Degrees(),
  [FunctionName.Radians]: new Radians(),
  [FunctionName.Mround]: new Mround(),
  [FunctionName.Combin]: new Combin(),
  [FunctionName.Permut]: new Permut(),
  [FunctionName.Quotient]: new Quotient(),
  [FunctionName.Clamp]: new Clamp(),
  [FunctionName.Rand]: new Rand(),
  [FunctionName.RandBetween]: new RandBetween(),
  [FunctionName.Gcd]: new Gcd(),
  [FunctionName.Lcm]: new Lcm(),
  [FunctionName.Product]: new Product(),
  [FunctionName.Sumsq]: new Sumsq(),
  [FunctionName.Hypot]: new Hypot(),
  [FunctionName.Median]: new Median(),
  [FunctionName.Large]: new Large(),
  [FunctionName.Small]: new Small(),
  [FunctionName.Stdev]: new Stdev(),
  [FunctionName.Var]: new Var(),

  // Text (extended)
  [FunctionName.Char]: new Char(),
  [FunctionName.Code]: new Code(),
  [FunctionName.Exact]: new Exact(),
  [FunctionName.Proper]: new Proper(),
  [FunctionName.Clean]: new Clean(),
  [FunctionName.Dollar]: new Dollar(),
  [FunctionName.Fixed]: new Fixed(),
  [FunctionName.RegExpMatch]: new RegExpMatch(),
  [FunctionName.RegExpExtract]: new RegExpExtract(),
  [FunctionName.TextAfter]: new TextAfter(),
  [FunctionName.Contains]: new Contains(),
  [FunctionName.StartsWith]: new StartsWith(),
  [FunctionName.EndsWith]: new EndsWith(),
  [FunctionName.PadStart]: new PadStart(),
  [FunctionName.PadEnd]: new PadEnd(),
  [FunctionName.Bin2Dec]: new Bin2Dec(),
  [FunctionName.Dec2Bin]: new Dec2Bin(),
  [FunctionName.Oct2Dec]: new Oct2Dec(),
  [FunctionName.Dec2Oct]: new Dec2Oct(),
  [FunctionName.Hex2Dec]: new Hex2Dec(),
  [FunctionName.Dec2Hex]: new Dec2Hex(),
  [FunctionName.NumberFormat]: new NumberFormat(),
  [FunctionName.HtmlEncode]: new HtmlEncode(),
  [FunctionName.HtmlDecode]: new HtmlDecode(),
  [FunctionName.Base64Encode]: new Base64Encode(),
  [FunctionName.Base64Decode]: new Base64Decode(),
  [FunctionName.UrlDecode]: new UrlDecode(),
  [FunctionName.Repeat]: new Repeat(),

  // Logical (extended)
  [FunctionName.IsBlank]: new IsBlank(),
  [FunctionName.IfBlank]: new IfBlank(),
  [FunctionName.IfError]: new IfError(),
  [FunctionName.True]: new True(),
  [FunctionName.False]: new False(),
  [FunctionName.IsNumber]: new IsNumber(),
  [FunctionName.IsText]: new IsText(),
  [FunctionName.IsDate]: new IsDate(),
  [FunctionName.IsNaN]: new IsNaN(),
  [FunctionName.IsFinite]: new IsFinite(),

  // DateTime (extended)
  [FunctionName.Quarter]: new Quarter(),
  [FunctionName.IsoWeekNum]: new IsoWeekNum(),
  [FunctionName.DayOfYear]: new DayOfYear(),
  [FunctionName.SetDate]: new SetDate(),
  [FunctionName.SetTime]: new SetTime(),
  [FunctionName.MakeDate]: new MakeDate(),
  [FunctionName.MakeTime]: new MakeTime(),
  [FunctionName.FormatDuration]: new FormatDuration(),
  [FunctionName.DateSubtract]: new DateSubtract(),
  [FunctionName.StartOfMonth]: new StartOfMonth(),
  [FunctionName.EndOfMonth]: new EndOfMonth(),
  [FunctionName.StartOfWeek]: new StartOfWeek(),
  [FunctionName.EndOfWeek]: new EndOfWeek(),
  [FunctionName.StartOfYear]: new StartOfYear(),
  [FunctionName.EndOfYear]: new EndOfYear(),
  [FunctionName.DatetimeIsValid]: new DatetimeIsValid(),
  [FunctionName.UnixTimestamp]: new UnixTimestamp(),
  [FunctionName.FromUnixTimestamp]: new FromUnixTimestamp(),

  // Array (extended)
  [FunctionName.ArraySum]: new ArraySum(),
  [FunctionName.ArrayAverage]: new ArrayAverage(),
  [FunctionName.ArrayMax]: new ArrayMax(),
  [FunctionName.ArrayMin]: new ArrayMin(),
  [FunctionName.ArraySlice]: new ArraySlice(),
  [FunctionName.ArrayReverse]: new ArrayReverse(),
  [FunctionName.ArrayIncludes]: new ArrayIncludes(),
  [FunctionName.ArrayCount]: new ArrayCount(),
  [FunctionName.ArrayFirst]: new ArrayFirst(),
  [FunctionName.ArrayLast]: new ArrayLast(),
  [FunctionName.ArraySort]: new ArraySort(),
  [FunctionName.ArrayIndexOf]: new ArrayIndexOf(),
  [FunctionName.ArrayDiff]: new ArrayDiff(),
  [FunctionName.ArrayLength]: new ArrayLength(),
  [FunctionName.ArrayHead]: new ArrayHead(),
  [FunctionName.ArrayTail]: new ArrayTail(),
  [FunctionName.ArrayIntersect]: new ArrayIntersect(),
  [FunctionName.ArrayUnion]: new ArrayUnion(),
  [FunctionName.StdevP]: new StdevP(),
  [FunctionName.VarP]: new VarP(),
  [FunctionName.Concat]: new Concat(),
};
