import { z } from 'zod';
import { FieldType, CellValueType } from '../constant';
import { FieldCore } from '../field';
import type { IFieldVisitor } from '../field-visitor.interface';
import { type IAttachmentFieldOptions } from './attachment-option.schema';
export declare const attachmentItemSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    path: z.ZodString;
    token: z.ZodString;
    size: z.ZodNumber;
    mimetype: z.ZodString;
    presignedUrl: z.ZodOptional<z.ZodString>;
    width: z.ZodOptional<z.ZodNumber>;
    height: z.ZodOptional<z.ZodNumber>;
    smThumbnailUrl: z.ZodOptional<z.ZodString>;
    lgThumbnailUrl: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
declare const attachmentItemRoSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    path: z.ZodOptional<z.ZodString>;
    token: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    size: z.ZodOptional<z.ZodNumber>;
    mimetype: z.ZodOptional<z.ZodString>;
    presignedUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    width: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    height: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    smThumbnailUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    lgThumbnailUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
export type IAttachmentItem = z.infer<typeof attachmentItemSchema>;
export type IAttachmentItemRo = z.infer<typeof attachmentItemRoSchema>;
export declare const attachmentCellValueSchema: z.ZodArray<z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    path: z.ZodString;
    token: z.ZodString;
    size: z.ZodNumber;
    mimetype: z.ZodString;
    presignedUrl: z.ZodOptional<z.ZodString>;
    width: z.ZodOptional<z.ZodNumber>;
    height: z.ZodOptional<z.ZodNumber>;
    smThumbnailUrl: z.ZodOptional<z.ZodString>;
    lgThumbnailUrl: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export declare const attachmentCellValueRoSchema: z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    path: z.ZodOptional<z.ZodString>;
    token: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    size: z.ZodOptional<z.ZodNumber>;
    mimetype: z.ZodOptional<z.ZodString>;
    presignedUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    width: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    height: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    smThumbnailUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    lgThumbnailUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>>;
export type IAttachmentCellValue = z.infer<typeof attachmentCellValueSchema>;
export type IAttachmentCellValueRo = z.infer<typeof attachmentCellValueRoSchema>;
export declare class AttachmentFieldCore extends FieldCore {
    type: FieldType.Attachment;
    options: IAttachmentFieldOptions;
    meta?: undefined;
    cellValueType: CellValueType;
    isMultipleCellValue: boolean;
    static CELL_VALUE_STRING_SPLITTER: string;
    static defaultOptions(): IAttachmentFieldOptions;
    static itemString(name: string, token: string): string;
    cellValue2String(cellValue?: unknown): string;
    convertStringToCellValue(_value: string, _ctx?: unknown): IAttachmentCellValue | null;
    repair(value: unknown): unknown;
    validateOptions(): z.ZodSafeParseResult<Record<string, never>>;
    validateCellValue(cellValue: unknown): z.ZodSafeParseResult<{
        name: string;
        token: string;
        id?: string | undefined;
        path?: string | undefined;
        size?: number | undefined;
        mimetype?: string | undefined;
        presignedUrl?: string | undefined;
        width?: number | undefined;
        height?: number | undefined;
        smThumbnailUrl?: string | undefined;
        lgThumbnailUrl?: string | undefined;
    }[] | null>;
    item2String(value: unknown): string;
    accept<T>(visitor: IFieldVisitor<T>): T;
}
export {};
